### ISSUE TITLE
Crash upon editing any lib/edit files and saving .atm in compiled app.

### ISSUE THREAD

**Issue by ryandagg** [Geozop/Furyband#1]
Thank you for making this available. So much wonderful nostalgia. 

Saving the automatizer rules works, but app crashes after saving and exiting the screen you can save from.

Modifying any of the text files in lib/edit, even just whitespace, leads to the app crashing when attempting to load a module.

I tried to build myself on windows but get over a hundred errors. Most are 
`fatal error C1083: Cannot open include file: 'sys/param.h': No such file or directory`

Unfortunately, my C++ skills are lacking.

**Comment by Geozop** [comment]
Nice to find there's another fan out there.

I can recreate the automatizer crash, but not the modifying of the edit files crash. I tried editing rules/whitespace in a_info and k_info, and it performed like normal. Could you give more detail on that?

"sys/param.h" is a linux header file. My guess is you're attempting to compile every single .c file in Visual Studio, but not every file should be used to compile for Windows. Actually, looks like my VS solution file idea is incomplete (the .vcxproj file is missing), so that's probably why you had to try it. I'll have to work on that too. If you can't wait, you could install Cygwin and use make with the makefile.cyg file. You will need to use Cygwin's installer to also install mingw64-x86_64-gcc-core. Yeah, it's almost not worth it.

**Comment by ryandagg** [comment]
I was able to find a work around for the changing lib/edit files. Deleting everything in lib/data after changing lib/edit leads to the app starting without issued. 

I probably should have just played the game as is instead of giving the Alchemy skill to every class... I like godly characters, no 2 ways about it.

**Comment by Geozop** [comment]
I wonder if it's a write permission problem. It might have to do with which folder it's in and if Windows is letting Furyband delete/edit files.

In any case, I fixed the automatizer crash. Not sure why it never crashed before, since the code was pretty bad (too large a buffer length given).

Yeah, alchemist is my favorite. I try to get that skill as a quest reward whenever possible. Anyway, let me know if anything else comes up.
